### ISSUE TITLE
It appears that after token expires error is reported 

### ISSUE THREAD

**Issue by leonbrag** [microsoftgraph/python-sample-auth#10]
`{'error': {'code': 'InvalidAuthenticationToken', 'message': 'CompactToken validation failed with reason code: 80049228.', 'innerError': {'request-id': 'c2920885-4c71-4dea-bee7-dbe21c52ec1e', 'date': '2018-08-02T21:52:02'}}}
`

**Comment by danielmanatal** [comment]
Did you figure out what's the problem, I am having same issue

**Comment by rayluo** [comment]
Each access token is typically good for 1 hour. After that you will need to either refresh it or just acquire a new one.
