### ISSUE TITLE
authorization request denied

### ISSUE THREAD

**Issue by blodemaster** [microsoftgraph/python-sample-auth#12]
Hi,

I run the `sample_adal.py` to play around with the AAD. However, after authorization, I got following when I was transferred to the `graphcall` path.

{'error': {'code': 'Authorization_RequestDenied', 'message': 'Insufficient privileges to complete the operation.', 'innerError': {'request-id': '15038357-2dee-45b7-9d84-a3adae7b7c47', 'date': '2018-12-12T21:43:28'}}}

Could someone please give me some hint about how to solve it?

Best regards

**Comment by blodemaster** [comment]
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/12708488/49924364-619d4580-feb6-11e8-9749-2807196c9457.png">
Here is the permisson I have granted to the Graph API

**Comment by blodemaster** [comment]
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/12708488/49924458-acb75880-feb6-11e8-89c8-547aa1b4ee21.png">
Here is the permission I have granted to Graph

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-pythondjangoapp for a Python sample.
