### ISSUE TITLE
OSError: [Errno 48] Address already in use

### ISSUE THREAD

**Issue by jtr216** [microsoftgraph/python-sample-auth#13]
Hi,
I am getting this error message `OSError: [Errno 48] Address already in use` when  I try running sample_requests.py or sample_graphrest.py.  How can I resolve this?

**Comment by odbalogun** [comment]
There's another application already running on that port. Most likely you're already running one of the scripts. Check your terminal/command-line sessions and end any running scripts then try again

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-pythondjangoapp for a Python sample.
