### ISSUE TITLE
Is there a way to get the authorization token through http requests?

### ISSUE THREAD

**Issue by AlphaTangoFoxtrot** [microsoftgraph/python-sample-auth#14]
I'm trying to read my Outlook emails and every example has me visiting a url and signing into my account using a frontend UI. Is there a way I can do all of this through http requests instead? Where I can sign in by sending in some kind of request payload?

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-pythondjangoapp for a Python sample.
