### ISSUE TITLE
flask.session empty

### ISSUE THREAD

**Issue by vincentchevrier** [microsoftgraph/python-sample-auth#15]
Python 3.7 with pip install requirements on flask-oauthlib (note there is currently a conflict with the request-oauthlib)

I am running the `sample_flask.py` as is.
My `config.py` is updated with an App registration from Azure.
The App registration is:
- type: Web app / API
- reply urls includes `http://localhost:5000/login/authorized`
- Required permission > Microsoft Graph > Sign in and read user profile

My config file has
```
CLIENT_ID = [ID from app registration above]
CLIENT_SECRET = [secret key from app registration]
REDIRECT_URI = 'https://localhost:5000/login/authorized'
AUTHORITY_URL = 'https://login.microsoftonline.com/[authority specific to my company]'
AUTH_ENDPOINT = '/oauth2/v2.0/authorize'
TOKEN_ENDPOINT = '/oauth2/v2.0/token'
RESOURCE = 'https://graph.microsoft.com/'
API_VERSION = 'v1.0'
SCOPES = ['User.Read'] 
```

The webserver starts up fine, I click login, it goes through the redirect, brings me to my organization page, credentials work fine, and then the redirect comes back to this function (`sample_flask.py`):

```
@APP.route('/login/authorized')
def authorized():
    """Handler for the application's Redirect Uri."""
    if str(flask.session['state']) != str(flask.request.args['state']):
        raise Exception('state returned to redirect URL does not match!')
    response = MSGRAPH.authorized_response()
    flask.session['access_token'] = response['access_token']
    return flask.redirect('/graphcall')
```

I can see that the `flask.request.args['state']` is correct and includes the `state` but the `flask.session` is now empty and causes this error:

```
  File "/Users/vincent/repos/python-sample-auth/sample_flask.py", line 37, in authorized
    if str(flask.session['state']) != str(flask.request.args['state']):
  File "/anaconda3/envs/flask-auth/lib/python3.7/site-packages/werkzeug/local.py", line 377, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
  File "/anaconda3/envs/flask-auth/lib/python3.7/site-packages/flask/sessions.py", line 84, in __getitem__
    return super(SecureCookieSession, self).__getitem__(key)
KeyError: 'state'
```

Somehow the `session` object gets emptied. If I print out `flask.session` within the `authorized` function it is an empty `<SecureCookieSession {}>`

**Comment by Hershill** [comment]
Having the same issue. Were you able to figure out why this was happening @vincentchevrier?

**Comment by vincentchevrier** [comment]
Sorry, never solved it

**Comment by TysonLinger** [comment]
I had the same issue with sample_flask.py. I created a new environment and changed one of the lines in the requirements.txt file to: "requests-oauthlib = "==1.1.0", reinstalled the packages, and now it is working.

Possibly relevant: 
https://github.com/lepture/flask-oauthlib/pull/388
https://github.com/lepture/flask-oauthlib/issues/390
https://github.com/lepture/flask-oauthlib/issues/391

I'm not sure if this is what fixed it or not, but give it a try.

**Comment by youdar** [comment]
having the same issue
flask.session['state']  get value hear

`@APP.route('/login')
def login():
    """Prompt user to authenticate."""
    flask.session['state'] = str(uuid.uuid4())
    return MSGRAPH.authorize(callback=config.REDIRECT_URI, state=flask.session['state'])` 

but the value doe not exist in 
`@APP.route('/login/authorized')
def authorized():
    """Handler for the application's Redirect Uri."""
    if str(flask.session['state']) != str(flask.request.args['state']):`

**Comment by QuentinDumont** [comment]
I face the same problem when I launch my app with the following link provided by Flask :
http://127.0.0.1:5000/

It however perfectly works with : 
http://localhost:5000
which is the information I gave to Microsoft Azure.

With which link are you guys trying ?

**Comment by zhanglei1172** [comment]
> I had the same issue with sample_flask.py. I created a new environment and changed one of the lines in the requirements.txt file to: "requests-oauthlib = "==1.1.0", reinstalled the packages, and now it is working.
> 
> Possibly relevant:
> [lepture/flask-oauthlib#388](https://github.com/lepture/flask-oauthlib/pull/388)
> https://github.com/lepture/flask-oauthlib/issues/390
> https://github.com/lepture/flask-oauthlib/issues/391
> 
> I'm not sure if this is what fixed it or not, but give it a try.

It works for me.

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-pythondjangoapp for a Python sample.
