### ISSUE TITLE
Add python sample for service authentication (no user interaction)

### ISSUE THREAD

**Issue by Borkason** [microsoftgraph/python-sample-auth#17]
I think it would be beneficial if you could provide a Python sample for service authentication (access without a user). This would be most interesting for sysadmins to create non-interactive automation tasks that cannot be solved done via PowerShell.

https://docs.microsoft.com/en-us/graph/auth-v2-service

**Comment by jmprieur** [comment]
@Borkason, did you see https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/sample/confidential_client_secret_sample.py and https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/dev/sample/confidential_client_certificate_sample.py ?

**Comment by Borkason** [comment]
@jmprieur no, I didn't. While the code may be working (haven't tried it yet), I don't believe this is helpful. People come to this repository from https://developer.microsoft.com/en-us/graph/get-started/python where it says:

> Python authentication samples for Microsoft Graph

So I believe that service authentication (non-interactive) should be included into the samples, simply because it's the sample repository that is linked at the official *getting started* page.

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-pythondjangoapp for a Python sample.
