### ISSUE TITLE
[sample_flask.py] ImportError: Cannot import name from 'werkzeug'

### ISSUE THREAD

**Issue by glarcina** [microsoftgraph/python-sample-auth#21]
![image](https://user-images.githubusercontent.com/21692347/74465370-4552bb00-4e63-11ea-87c6-736cf9d01c1e.png)

This occurred on Python 3.6 and 3.7.

Looks like **flask_oauthlib** has been deprecated and has changed to **authlib** so no point reporting this issue on that repo.

However, I resolved this error by including the specific modules in **\Python3x\Lib\site-packages\flask_oauthlib\client.py**:

`from werkzeug.urls import url_quote, url_decode, url_encode`
`from werkzeug.http import parse_options_header`
`from werkzeug.utils import cached_property`

This was the only roadblock I experienced using this example - hope it helps someone.

**Comment by jasonjoh** [comment]
Closing this issue as we are archiving this repository. Please see https://github.com/microsoftgraph/msgraph-training-pythondjangoapp for a Python sample.
