### ISSUE TITLE
Are there any methods of authing that dont require flask?

### ISSUE THREAD

**Issue by strunker** [microsoftgraph/python-sample-auth#5]
I am writing an Alexa skill that runs in aws lambda. I haven't tested this, but I don't believe flask will work very well there.

When you auth via PS you simply make rest requests, im not sure why almost every method of authing in python reference flask. 

Thanks

**Comment by tsekineMcp** [comment]
I have the same problem, especially, I got a KeyError [at this line](https://github.com/microsoftgraph/python-sample-auth/blob/882a250140a402a1fc4bfb4f996f67462e72ad64/sample_flask.py#L37) .

Other samples seem to work well.

**Comment by dmahugh** [comment]
@strunker there are samples in the repo that use Bottle instead of Flask, but for an Alexa skill I assume you're looking for an auth solution that doesn't require a web app at all? One option would be to use device flow as covered in this sample: [https://github.com/microsoftgraph/python-sample-console-app](https://github.com/microsoftgraph/python-sample-console-app). Will that work for what you need to do?

**Comment by dmahugh** [comment]
@tsekineMcp Sorry for the delay, just saw your issue. I'm not able to re-create that error. The 'state' entry should be set on [this line](https://github.com/microsoftgraph/python-sample-auth/blob/882a250140a402a1fc4bfb4f996f67462e72ad64/sample_flask.py#L31) when you log in. I'll look into this further and follow up.

**Comment by strunker** [comment]
@dmahugh 
Ill take a look at the console app example. I was really hoping for a sample that uses request oathlib and just uses application credentials.

I feel like the user based permissions are a bit much on graph honestly kind of over complicates it a bit at times. And that flat out wont work for running from within Lamda or in any type of automated script so app creds are the only way to go.

I couldnt find a sample that utilized that authentication method though.

thanks much.

**Comment by dmahugh** [comment]
@strunker It sounds like what you want is the [client credentials](https://github.com/AzureAD/azure-activedirectory-library-for-python#acquire-token-with-client-credentials) auth flow. Note however that that requires configuring a service principal, which may be clumsy for some users. The device flow in the [console app sample](https://github.com/microsoftgraph/python-sample-console-app) requires the user to go to a browser (on any device - their phone, for example) and enter a code at aka.ms/devicelogin, but if you include the _offline_access_ scope then you can get a refresh token and use that to refresh the access token going forward. So entering the device code would just be an initial configuration step, and then you could provide a seamless experience going forward.

We're interested in enabling a variety of Python scenarios, so feel free to log issues with any ideas you have, or you can email me at **DMahugh** at Microsoft.com with suggestions as well. Thanks for the feedback.

**Comment by tsekineMcp** [comment]
@dmahugh Thank you for replying. For some reason, though I could not keep session, but my app is needed to run in background. Therefore, I have adopted other way and the way goes well. Thank you very much!
